## EDA

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv('spam.csv')

In [8]:
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [9]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [10]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [11]:
df.rename(columns={'v1':'output','v2':'text'},inplace=True)

In [12]:
df

     output                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [13]:
df.isnull().sum()

output    0
text      0
dtype: int64

In [14]:
df.shape

(5572, 2)

In [15]:
df.duplicated().sum()

np.int64(403)

In [16]:
df=df.drop_duplicates()

In [17]:
df

     output                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [18]:
df.duplicated().sum()

np.int64(0)

## Feature Engineering

In [19]:
!pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [20]:
import sklearn

In [21]:
! pip install nltk

Requirement already satisfied: nltk in c:\users\amardeep\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\amardeep\anaconda3\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\amardeep\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\amardeep\anaconda3\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\amardeep\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\amardeep\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [22]:
import nltk

In [23]:
from nltk.stem.porter import PorterStemmer

In [24]:
p=PorterStemmer()

In [25]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Amardeep\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
from nltk.corpus import stopwords

In [27]:
from nltk import word_tokenize

In [28]:
def transform(text):
    
    # If already tokenized (list), convert to string
    if isinstance(text, list):
        text = " ".join(text)
    
    text = text.lower()

    words = word_tokenize(text)

    stop_words = set(stopwords.words('english'))
    words = [p.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

In [29]:
transform("hey bro i am shubh")

'hey bro shubh'

In [30]:
df['text']=df['text'].apply(transform)

C:\Users\Amardeep\AppData\Local\Temp\ipykernel_11636\70249340.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text']=df['text'].apply(transform)

In [31]:
df.head()

  output                                               text
0    ham  go jurong point , crazi .. avail bugi n great ...
1    ham                      ok lar ... joke wif u oni ...
2   spam  free entri 2 wkli comp win fa cup final tkt 21...
3    ham        u dun say earli hor ... u c alreadi say ...
4    ham         nah n't think goe usf , live around though

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tfidf=TfidfVectorizer(max_features=500)

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
label=LabelEncoder()

In [36]:
df['output']=label.fit_transform(df['output'])

C:\Users\Amardeep\AppData\Local\Temp\ipykernel_11636\2604714714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['output']=label.fit_transform(df['output'])

In [37]:
df

      output                                               text
0          0  go jurong point , crazi .. avail bugi n great ...
1          0                      ok lar ... joke wif u oni ...
2          1  free entri 2 wkli comp win fa cup final tkt 21...
3          0        u dun say earli hor ... u c alreadi say ...
4          0         nah n't think goe usf , live around though
...      ...                                                ...
5567       1  2nd time tri 2 contact u. u å£750 pound prize ...
5568       0                         ì_ b go esplanad fr home ?
5569       0                      piti , * mood . ... suggest ?
5570       0  guy bitch act like 'd interest buy someth els ...
5571       0                                   rofl . true name

[5169 rows x 2 columns]

In [38]:
x=tfidf.fit_transform(df['text'])
y=df['output']

In [39]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26749 stored elements and shape (5169, 500)>

Test Train

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [42]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 18545 stored elements and shape (3618, 500)>

# Model training

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [44]:
svc = SVC(kernel= "sigmoid", gamma  = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5)
lrc = LogisticRegression(solver = 'liblinear', penalty = 'l1')
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2 )
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)    
xgb  = XGBClassifier(n_estimators = 50, random_state = 2)

In [45]:
clfs = {
    'SVC': svc,
    'KNN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'Adaboost': abc,
    'Bgc': bc,
    'ETC': etc,
    'GBDT': gbdt,
    'xgb': xgb
    
}

In [46]:
from sklearn.metrics import accuracy_score, precision_score
def train_classifier(clfs, X_train, y_train, X_test, y_test):
    clfs.fit(X_train,y_train)
    y_pred = clfs.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    return accuracy , precision

In [47]:
accuracy_scores = []
precision_scores = []
for name , clfs in clfs.items():
    current_accuracy, current_precision = train_classifier(clfs, X_train, y_train, X_test, y_test)
    print()
    print("For: ", name)
    print("Accuracy: ", current_accuracy)
    print("Precision: ", current_precision)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For:  SVC
Accuracy:  0.9774339136041263
Precision:  0.9556650246305419

For:  KNN
Accuracy:  0.9136041263700838
Precision:  0.967391304347826

For:  NB
Accuracy:  0.9774339136041263
Precision:  0.9601990049751243

For:  DT
Accuracy:  0.9400386847195358
Precision:  0.8628571428571429

For:  LR
Accuracy:  0.970341715022566
Precision:  0.9484536082474226

For:  RF
Accuracy:  0.9793681495809156
Precision:  0.9747474747474747

For:  Adaboost
Accuracy:  0.9161831076724694
Precision:  0.8260869565217391

For:  Bgc
Accuracy:  0.9632495164410058
Precision:  0.8755760368663594

For:  ETC
Accuracy:  0.9800128949065119
Precision:  0.9565217391304348

For:  GBDT
Accuracy:  0.9606705351386202
Precision:  0.9877300613496932

For:  xgb
Accuracy:  0.973565441650548
Precision:  0.9637305699481865